name: Test Coverage
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        run: |
          install.packages(c("covr", "devtools", "remotes", "jsonlite", "dplyr"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Generate coverage badge data
        run: |
          coverage_results <- devtools::test_coverage()
          percent <- round(covr::percent_coverage(coverage_results), 1)

          # create shields.io compatible json
          shield_data <- list(
            schemaVersion = 1,
            label = "coverage",
            message = paste0(percent, "%"),
            color = dplyr::case_when(
              percent >= 80 ~ "brightgreen",
              percent >= 60 ~ "yellow",
              percent >= 40 ~ "orange",
              TRUE ~ "red"
            )
          )

          dir.create("coverage", showWarnings = FALSE)
          jsonlite::write_json(shield_data, "coverage/shield.json",
                              pretty = TRUE, auto_unbox = TRUE)
        shell: Rscript {0}

      - name: Commit coverage data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add coverage/shield.json
          git diff --staged --quiet || git commit -m "update coverage badge data"
          git push
